[package]
name = "open_platform_fighter"
version = "0.1.0"
authors = ["ramsir3 <ramsir3@gmail.com>"]
# build = "build.rs" 

[dependencies]
piston_window = "0.85.0"
enum-display-derive = "0.1.0"

# [build-dependencies]
# inflections = "1.1.1"